---
title: "class08-2"
author: "Andrei Kedich"
date: "27 10 2020"
output: html_document
---

```{r}
streets <- read_xlsx('tverobl_streets.xlsx') %>% 
  mutate(dir = ifelse(dir > 180, dir - 180, dir),
         cdir = circular(dir, 
                         units = 'degrees',
                         zero = pi/2,
                         rotation = 'clock')) 

```

```{r}
towns = unique(streets$town)

plot_directions = function(dirs, title, subtitle) {
  kden = kern.den.circ(dirs)

  peak = findpeaks(kden$y, sortstr = T)[1,2] 
  modal = kden$x[peak]
  modal = ifelse(modal < 0, 360 + modal, modal)
  
  
  # раскладываем на составляющие для отрисовки линии
  xp = sin(pi * modal / 180)
  yp = cos(pi* modal / 180)
  
  plot.circular(dirs, 
       cex = 0.3, 
       stack = TRUE, 
       sep = 0.035,
       axes = FALSE,
       shrink = 1.25,
       main = title,
       sub = subtitle)
  
  rose.diag(dirs, 
            bins = 24, 
            col = 'gray70',
            border = 'gray30',
            prop = 2, 
            add = TRUE, 
            tick = FALSE,
            lwd = 0.5)
  
  lines(kden, shrink = 3, 
        join = F, col = 'steelblue')
  
  lines(c(0, xp), c(0, yp),
        lwd = 2, col = 'orangered')
  
  text(x = 1.4 * xp, y = 1.4 * yp, 
       col = 'orangered',
       labels = paste0(round(modal, 0), '°')) 
}

for (t in towns) {
  dirs = streets %>% 
    filter(town == t) %>% 
    pull(cdir)
  plot_directions(c(dirs, dirs + 180), 'Направления улиц', t) 
}
```

